/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include "ara/gnss/gnssinfoserviceinterface_common.h"

namespace ara {
namespace gnss {
constexpr ara::com::ServiceIdentifierType GnssInfoServiceInterface::ServiceIdentifier;
constexpr ara::com::ServiceVersionType GnssInfoServiceInterface::ServiceVersion;
} // namespace gnss
} // namespace ara
