/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include <ara/imu/imuinfoserviceinterface_common.h>

namespace ara {
namespace imu {
constexpr ara::com::ServiceIdentifierType ImuInfoServiceInterface::ServiceIdentifier;
constexpr ara::com::ServiceVersionType ImuInfoServiceInterface::ServiceVersion;
} // namespace imu
} // namespace ara
