/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#include <ara/lidar/lidarserviceinterface_common.h>

namespace ara {
namespace lidar {
constexpr ara::com::ServiceIdentifierType LidarServiceInterface::ServiceIdentifier;
constexpr ara::com::ServiceVersionType LidarServiceInterface::ServiceVersion;
} // namespace lidar
} // namespace ara
